version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - '8080:8080'
    volumes:
      - .:/app
    environment:
      - GIN_MODE=debug
